backend = "glx";
vsync = true;

# Opacity
active-opacity = 1;
inactive-opacity = 1;
frame-opacity = 1;

opacity-rule = [
  "70:class_g = 'Gnome-terminal'"
];

####### blur
blur-background = true;
blur-method = "dual_kawase";
blur-strength = 8;
blur-background-exclude = [
  # "window_type = 'dock'",
  "class_g = 'i3-frame'"
];

####### Fading
fading = true;
fade-delta = 4;
no-fading-openclose = false;
fade-exclude = [ ];

####### Corners
corner-radius = 15;

rounded-corners-exclude = [
  "class_g = 'i3bar'",
  "class_g = 'Polybar'"
];

glx-use-copysubbuffer-mesa = true;

glx-copy-from-front = true;
glx-swap-method = 2;
xrender-sync = true;
xrender-sync-fence = true;
